name: Build and Push plugin

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'
  workflow_dispatch:

env:
  PLUGIN_NAME: ${{ github.event.repository.name }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Install dependencies
        run: pnpm install

      - name: Build plugin
        run: pnpm run build

      - name: Package plugin
        run: |
          set -uexo pipefail
          VERSION=$(node -p "require('./package.json').version")
          OUT_DIR="out"
          STAGE_DIR="${OUT_DIR}/${PLUGIN_NAME}"
          ZIP_ARCHIVE="${PLUGIN_NAME}-v${VERSION}.zip"

          mkdir -p ${STAGE_DIR}

          cp -r dist "${STAGE_DIR}/dist"
          cp main.py "${STAGE_DIR}/main.py"
          cp plugin.json "${STAGE_DIR}/plugin.json"
          cp package.json "${STAGE_DIR}/package.json"
          cp license "${STAGE_DIR}/license"
          cp readme.md "${STAGE_DIR}/readme.md"

          cd "${OUT_DIR}"
          zip -r -X "${ZIP_ARCHIVE}" "${PLUGIN_NAME}"

      - name: Create release
        uses: softprops/action-gh-release@v2.3.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.event.repository.name }} ${{ github.ref_name }}
          generate_release_notes: true
          prerelease: false
          files: out/${{ env.PLUGIN_NAME }}-*.zip
